chef/knife-windows

lib/chef/knife/bootstrap/windows-chef-client-msi.erb, lib/chef/knife/core/windows_bootstrap_context.rb, lib/chef/knife/winrm.rb, spec/unit/knife/winrm_spec.rb
chef-client gets installed on the node but node doesn't get registered on the hosted chef account.
=> knife bootstrap windows winrm fails with Bad HTTP error

lib/chef/knife/bootstrap/windows-chef-client-msi.erb, lib/chef/knife/core/windows_bootstrap_context.rb
```
DEBUG: Found bootstrap template in C:/opscode_live/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-windows-1.0.0.dev.0/lib/chef/knife/bootstrap
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `version' for nil:NilClass
```
Implemented changes to fix above issue
=> Fixed bug related to chef gem version check

lib/chef/knife/core/windows_bootstrap_context.rb, lib/chef/knife/winrm.rb, lib/knife-windows/path_helper.rb, spec/unit/knife/winrm_spec.rb
Hide empty error messages received during winrm communication.
like in bootstrap -
104.40.81.154 "Rendering "C:\Users\adamed\AppData\Local\Temp\bootstrap-22859-1421430971.bat" chunk 14" 
104.40.81.154
=> Changes to hide empty error messages from winrm

lib/chef/knife/windows_cert_generate.rb, spec/unit/knife/windows_cert_generate_spec.rb
Fix for issue https://github.com/chef/knife-windows/issues/163
Azure requires base64 encoded `pfx` file: https://msdn.microsoft.com/en-us/library/azure/ee460817.aspx
Since we were using `der` file for that purpose only, we should make the extension accurate.
=> Changed .der extension to .b64

lib/chef/knife/winrm.rb, spec/unit/knife/winrm_spec.rb
The issue is introduced after removing `em-winrm` .  The bootstrap output missing some details like-downloading and installing chef-client package, running chef-client on node etc.
Added changes to display all bootstrap process data.
=> Fixed bootstrap output display issues

README.md
Windows 2008r2 and earlier require an extra configuration.
We should set  MaxTimeoutms >= 30000 to avoid WinRM::WinRMHTTPTransportError: Bad HTTP response error while bootstrapping
=> Updated Readme for setting MaxTimeoutms for windows 2008r2

lib/chef/knife/bootstrap/windows-chef-client-msi.erb
The command to create trusted_certs folder during bootstrapping seems to have been copied from a UNIX bootstrapping template, which won't run properly in a Windows batch file.
=> Invalid mkdir command in bootstrap template

lib/chef/knife/bootstrap/windows-chef-client-msi.erb, lib/chef/knife/core/windows_bootstrap_context.rb
The helper for accessing trusted_certs content was renamed to `trusted_certs_script` in 583a2b2. For some reason this was changed back to `trusted_certs` in commit c09a2b2. Without this fix bootstrapping fails with:
NameError: undefined local variable or method `trusted_certs' for #<Chef::Knife::Core::WindowsBootstrapContext:0x007fcd54522910>
/cc @adamx @btm
=> Fix trusted_certs regression introduced by c09a2b2

Gemfile, README.md, knife-windows.gemspec, lib/chef/knife/windows_helper.rb, lib/chef/knife/winrm.rb, lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, lib/chef/knife/winrm_shared_options.rb, lib/chef/knife/wsman_endpoint.rb, lib/chef/knife/wsman_test.rb, spec/spec_helper.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb, spec/unit/knife/wsman_test_spec.rb
This adds a command "knife wsman test" to help verify connectivity to remote WinRM endpoints.  Currently this can be tested from Windows nodes with PowerShell, but it is more difficult to validate connectivity cross platform.  This command will validate that the remote port is reachable and listening for management requests similar to Test-Wsman in PowerShell. 
Targets can be specified manually (as per the knife winrm command) or use search to identify target nodes.
=> Adding knife wsman test to validate WSMAN/WinRM availability

lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_knife_base.rb, spec/unit/knife/winrm_spec.rb
:default setting for --winrm-port option was removed on master and its causing to set winrm_port to nil in knife ec2 server create. Updated code to set default option of --winrm-port to 5985 in option and if --winrm-transport value is ssl then to 5986. And removed set default part from winrm_knife_base.rb
=> Updated code for setting winrm port default option

knife-windows.gemspec, lib/knife-windows/version.rb
Previously we pinned to ~> 0.2, which would have pulled in winrm-s 0.3.0.
winrm-s 0.3.0 depends on winrm 1.3.0, which has some major changes.
Since knife-windows 1.0.0 is a major change, including the removal of em-winrm,
I want to stabilize the knife-windows 0.8.x branch.
=> make winrm-s dep more strict on knife-windows 0.8.x

lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/core/windows_bootstrap_context.rb
Allow choose how to install chef-client, as regular appplication or as service
Add --install-as-service option in your bootstrap command line and MSI will install and enable the service on Windows.
it should resolve #202
=> Possibility to bootstrap with install as service option

.gitignore, .travis.yml, Gemfile, appveyor.yml, ci.gemfile, knife-windows.gemspec
We're adding code to knife-windows to support features like validatorless bootstrap (#224) that only works on Chef 12, so we need to be able to test with Chef 12 so we can ensure we raise errors or actually work as appropriate.
=> Update Travis/Appveyor to test Chef 11 + Chef 12

appveyor.yml
This is breaking bundler when it has to do a git checkout
=> Disable caching in appveyor

lib/chef/knife/bootstrap/windows-chef-client-msi.erb, lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/core/windows_bootstrap_context.rb, spec/functional/bootstrap_download_spec.rb, spec/spec_helper.rb, spec/unit/knife/bootstrap_template_spec.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb
=> validatorless bootstrap

spec/functional/bootstrap_download_spec.rb, spec/spec_helper.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
Replaces #235.
* Rebased against master with the new validatorless bootstrap support
* Updated the platform helpers in the spec tests to match Chef's bikeshed
=> Fix null validation_key error

lib/chef/knife/bootstrap_windows_base.rb
Adding --hint option to 'knife bootstrap windows" command  in order work
with windows cloud VM instances (like ec2) and to get cloud specific
ohai attributes (like public ipaddress) and save those to node object on
chef.
=> Adding --hint option to bootstrap 

lib/chef/knife/winrm_base.rb
It currently uses -i, which the identity file also uses. -T looks available
per the `knife windows bootstrap winrm --help` output.
Fixes #110 
@chef/client-windows, @jamescott
=> Change kerberos keytab short option to -T to resolve conflict

lib/chef/knife/winrm_knife_base.rb, spec/unit/knife/winrm_spec.rb
The error message regarding negotiate when on non-windows platforms
specifies an incorrect option alternative. This commit improves that
error message.
=> Update winrm error message to provide correct options

spec/functional/bootstrap_download_spec.rb
Adding a test to check whether the msi_url flag can handle a path with a space.
@adamedx @schisamo @ksubrama
=> Update bootstrap test to include msi_url with space

lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/winrm_knife_base.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb, spec/unit/knife/winrm_spec.rb
this prevents unencrypted negotiate auth on non windows from failing and improves the warning message. To prevent this warning from being displayed on every winrm command during bootstrap, the winrm bootstrap command is refactored to validate this authentication method on its own and then call a single winrm session for all winrm calls instead of calling run on a new winrm knife instance for each call that would perform the validation each time.
=> fixes #280 preventing unencrypted negotiate auth on non windows

lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/winrm_knife_base.rb, spec/unit/knife/winrm_spec.rb
Under some circumstances, negotiate authentication will fail using a local account if the "local domain" is not specified. Users may likely neglect to prefix a local username with the machine name or IP address and its confusing why access is being denied. This PR detects if an explicit domain is not being sent when using negotiate and if not, uses the short form `.\{user}` username.
=> prefix local usernames with dot domain notation when using negotiate

lib/chef/knife/winrm_session.rb, spec/unit/knife/winrm_session_spec.rb
The `http_proxy` config value set in client.rb or knife.rb is the ubiquitous way to define the proxy to use for outgoing traffic from local calls into the chef API.  See https://github.com/chef/chef/blob/master/lib/chef/http/basic_client.rb#L99 and https://github.com/chef/chef/blob/master/lib/chef/http/basic_client.rb#L140. 
This covers all chef client to chef server communication in `chef-client` runs and includes the `knife bootstrap` http calls to the chef server. Its the same config value that the `bootstrap_proxy` argument of `knife bootstrap` sets on a bootstrapped node's client.rb. 
`knife winrm` and `knife windows bootstrap` calls do not currently leverage this config setting because their calls don't go through the chef http APIs but go through the winrm gem. The winrm gem does …
=> use configured proxy settings for all winrm sessions

lib/chef/knife/wsman_test.rb
ChefDK carries along 2 versions of nokogiri and the older one is hard pinned to mini_portile 0.6.0 so we also get 2 versions of mini_portile as well which is what eventually causes this warning. The root problem to be addressed separately is the fact that chefDK grabs 2 versions of nokogiri and based on a `gem dependency -R nokogiri` there appears to be no good reason for this and we should just get the latter.
However I see this as a worthwhile change to quicky fix the problem here and deferring gem loading is a good thing in this case.
=> defer nokogiri require

lib/chef/knife/core/windows_bootstrap_context.rb, spec/assets/win_template_rendered_with_bootstrap_install_command_on_12_5_client.txt, spec/assets/win_template_rendered_without_bootstrap_install_command_on_12_5_client.txt, spec/functional/bootstrap_download_spec.rb
I believe this is the commit in Chef (release in 12.5.1) that caused the regression in knife-windows: https://github.com/chef/chef/commit/14d7baab6365e0b4146990a5306f80a7f0d09a82 -- cc @danielsdeleo. I'm just not exactly sure how...
=> Address regression caused by chef client 12.5 environment argument

lib/chef/knife/bootstrap_windows_base.rb
The policy file work introduced a new `validate_options!` method in `Knife::Bootstrap` that this calls in the `bootstrap` method. However, if using a pre 12.5 chef client, this method will not exist. So this PR adds that method to the bootstrap base module and simply calls `super` so if its in `Knife::Bootstrap` it will be called otherwise nothing happens.
=> make knife-windows backwards compatible with most current chef clients

lib/chef/knife/winrm.rb, lib/chef/knife/winrm_knife_base.rb, spec/functional/bootstrap_download_spec.rb, spec/unit/knife/winrm_spec.rb, spec/unit/knife/wsman_test_spec.rb
There is currently a bug in v1.0 that does not pass the prompted password to the winrm session.
=> ensure prompted password is passed to winrm session

lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/winrm.rb, lib/chef/knife/winrm_knife_base.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb, spec/unit/knife/winrm_spec.rb
This fixes #311 and consolidates error handling logic to ensure both knife winrm and knife winrm bootstrap follow the same path.
=> knife winrm bootstrap should not swallow failed exit codes

lib/chef/knife/bootstrap_windows_base.rb
Specifying --bootstrap-vault-item etc. on bootstrap to encrypt keys for a new node did not work because chef-vault was executed before the client has been created.
=> Vault updates need to happen after the client has been built.

lib/chef/knife/winrm_session.rb, spec/unit/knife/bootstrap_options_spec.rb
this fixes #323 broken by https://github.com/chef/chef/commit/85d0407a16fa4dfc479d550a96355a6d11f4f551
=> retrofit proxy configuration to work with 12.6

Gemfile, README.md, knife-windows.gemspec, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb
This is a WIP PR dependent on the following downstream PRs:
https://github.com/WinRb/rubyntlm/pull/26
https://github.com/WinRb/WinRM/pull/144
The above PRs allow the winrm gem to provide sspinegotiate authentication and eliminates the need for the winrm-s monkey patches. the winrm changes work with the current httpclent API as is injecting the appropriate headers so no patches needed for httpclient. Further, the winrm changes leverage the rubyntlm gem which implements negotiate authentication in pure ruby. This allows us to leverage negotiate on linux workstations and do away with the OS checks and warnings regarding plaintext on linux.
cc @sneal @zenchild
=> drop winrm-s dependency and allow both windows and linux to use negotiate auth

lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/core/windows_bootstrap_context.rb
This is required to make the tests pass for chef-client
changes
=> Add fips flag to boostrap

spec/unit/knife/bootstrap_options_spec.rb
The fips flag is causing tests to fail because it is expecting it
in 12.6, however it's only in current master https://github.com/chef/chef/commit/58112e1210cac991e7a9cf434c74ece0aa97414d
and will be part of the 12.7 release.
=> Ignore the FIPS flag in tests

knife-windows.gemspec, lib/chef/knife/wsman_test.rb, spec/unit/knife/wsman_test_spec.rb
This makes the following fixes to `wsman test`:
* Do not swallow deeper http errors but send to verbode
* Do not prompt for password
* honor `--winrm-ssl-verify-mode verify_none`
* replace nokogiri with rexml
=> fixes wsman test and death to nokogiri

lib/chef/knife/wsman_test.rb
This change attempts to take some more "guess work" out of SSL verification errors. It also refactors the huge `verify_wsman_accessiblity_for_nodes` to smaller methods.
=> add more guidance around possible ssl verification issues

lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
If knife has set fips mode, make sure to add it to
the client.rb during bootstraps
Tested with basic auth + ssl transport
Some notes:
* ntlm authentication does not work. It uses MD4 and RC4
at some point. When asking openssl to do any of these
operations at any point while in fips mode, ruby will
refuse the request and raise. What this means is that
users will have to use basic auth over ssl or potentially
kerberos.
=> Knife bootstrap includes `fips true` when in fips mode

README.md, lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, spec/unit/knife/bootstrap_options_spec.rb
This adds a minor fixup to @hh's PR #298 and tweaks the readme just a bit.
The `ssl_fingerprint` option was added in winrm 1.6 and this makes it accessible from knife.
=> add support for winrm's new  ssl fingerprint option

.travis.yml, appveyor.yml, spec/assets/win_template_rendered_with_bootstrap_install_command.txt, spec/assets/win_template_rendered_without_bootstrap_install_command.txt
travis and appveyor are failing due to chef-zero requiring ruby 2.1.0. Since chef only tests against 2.1 and 2.2 now, we'll do the same here.
I'm also pinning bundler since the latest is broken on windows but a new release is imminent: https://github.com/bundler/bundler/pull/4479#issuecomment-215901069
=> Update to same rubies that chef uses

CHANGELOG.md, lib/chef/knife/winrm_session.rb, lib/chef/knife/wsman_test.rb, lib/knife-windows/version.rb, spec/dummy_winrm_service.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb, spec/unit/knife/wsman_test_spec.rb
Currently it is not possible for winrm calls to validate ssl certificates in the user's `trusted_certificates` folder. This has confused several users because while calls to `knife ssl check` leads ione to believe that a ssl certificate is trusted, subsequent bootstraps and `knife winrm` calls fail unless they turn off ssl validation.
This applies the `Chef::HTTP::DefaultSSLPolicy` to the winrm `HTTPClient` connection and therefore honors all certificates in the trusted_certs folder.
Admittedly the implementation here is quite hacky as it has to get to the `HTTPClient` via direct instance variable inspection. While I could expose those in winrm, that would require a minor version release and I'm trying to keep winrm releases at bay in order to focus on winrm v2.
=> Honor the chef ssl_policy when making winrm calls

Gemfile, ci.gemfile, lib/chef/knife/bootstrap_windows_base.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb
Done. json attributes passed through --json-attributes-file option were not getting set into config object and so the attributes passed were then missing from the first_boot.json file.
=> Added code and corresponding RSpecs to read the json attributes from the --json-attributes-file option.

lib/chef/knife/bootstrap/windows-chef-client-msi.erb
During knife windows bootstrapping of windows 64 bit machine using `ssh` protocol, the code is not able to determine the  architecture properly, `PROCESSOR_ARCHITECTURE` value returns `x86(32bit)` instead of `AMD64(64 bit)`.
The behaviour is due to WOW64, added more validation to detect the architecture properly.
Following are values for various scenarios:- 
Environment Variable      	 | 32bit Native	| 64bit Native	|  WOW64
PROCESSOR_ARCHITECTURE   	 |   x86        |    AMD64      |  x86
PROCESSOR_ARCHITEW6432     	 | undefined    |   undefined	|  AMD64
Reference:- https://blogs.msdn.microsoft.com/joshwil/2004/03/11/as-promised-what-is-the-wow64-and-what-does-it-mean-to-managed-apps-that-you-run-on-64bit-machines/
=> Fix for architechture detection issue for 64 bit

lib/chef/knife/bootstrap/windows-chef-client-msi.erb
During `knife bootstrap windows ssh` command for win 2008 64 bit, the command hangs at chef-client download through powershell command called through the bat file.
Setting InputFormat value to None in the powershell command resolved the issue and the bootstrap succeeded
=> Fixed win 2008 64bit ssh bootstrap command hanging 

README.md, knife-windows.gemspec, lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, spec/dummy_winrm_connection.rb, spec/functional/bootstrap_download_spec.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb
This uses the just released winrm v2 gems and allows users to specify a winrm shell. This can be `cmd`, `powershell`, or `elevated`.  `cmd` is the default. `elevated` will run commands via a powershell based scheduled task.
=> Use winrm v2 and allow users to pass a shell

README.md
Added the `--msi-url` option to the README. I ran into the problem myself and only found the solution by looking at knife-windows issues and forum posts like these:
* https://github.com/chef/knife-windows/issues/324
* https://discourse.chef.io/t/bootstrap-a-node-without-internet-access/7373/4
I believe it is an issue common enough to warrant a bit of documentation.
=> Add documentation of the --msi-url option

.travis.yml, Gemfile, README.md, appveyor.yml, knife-windows.gemspec, lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, spec/unit/knife/winrm_session_spec.rb
Older Windows versions prior to 2008R2 fail on the default UTF-8 codepage (65001). This PR allows users to pass a custom codepage. Typically for en-US users, `437` should be used for 2008 R1. This PR levereges the newly released WinRM 2.1.0 which exposes codepage and other shell options for the `:cmd` based shell.
=> Allow a custom codepage to be specified and passed to the cmd shell

README.md, lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/winrm.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_session.rb, lib/chef/knife/winrm_shared_options.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb
Until the native WinRM libraries support concurrent connections, add simple threading to handle parallel connections. 
Fixes #348
Signed-off-by: Tom Duffield <tom@chef.io>
=> Add concurrency support to knife-windows

.travis.yml, appveyor.yml, ci.gemfile, lib/chef/knife/core/windows_bootstrap_context.rb, spec/assets/win_template_rendered_with_bootstrap_install_command.txt, spec/assets/win_template_rendered_with_bootstrap_install_command_on_12_5_client.txt, spec/assets/win_template_rendered_without_bootstrap_install_command.txt, spec/assets/win_template_rendered_without_bootstrap_install_command_on_12_5_client.txt, spec/assets/win_template_rendered_without_bootstrap_install_command_on_13_client.txt, spec/functional/bootstrap_download_spec.rb, spec/spec_helper.rb, spec/unit/knife/bootstrap_options_spec.rb
Fixes issue when bootstrapping windows systems failing with the message: `The input line is too long.`.  
This is triggered by a "very" long `%PATH%` environment variable getting expanded at execution and causing the command being execute to become longer than the allowed size. 
We only need enough of the path set to be to run chef-client and doesn't persist to the system.
Signed-off-by: Will Fisher <wfisher@chef.io>
=> Change the %PATH% env to use windows default values

spec/unit/knife/bootstrap_options_spec.rb
Fix the specs by ignoring DEPRECATED options "distro" & "template_file" & by ignoring unimplemented option in knife-windows i.e "bootstrap_preinstall_command".
Fix for issue https://github.com/chef/chef/issues/7125
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
=> Fix the specs by ignoring DEPRECATED & unimplemented options

lib/chef/knife/bootstrap/windows-chef-client-msi.erb, spec/spec_helper.rb
**Description**
- Added windows 2016 support.
- Added windows 2012r2 support.
- Added windows 10 support.
- If windows version is unknown made windows 2012r2 as default.
**Fixed issue**
Fixes https://github.com/chef/knife-windows/issues/441
**Testing**
Testing for other windows environment are completed.
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
=> MSYS-831 : Fixed windows detection code for windows 2016, windows 2012r2

.expeditor/config.yml
Cleanup branches on PR merge
Enable minor version bumping
Add a changelog header for things that aren't yet pushed
Remove old labels
Fix deprecations
=> Update expeditor config

.travis.yml, appveyor.yml, lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/bootstrap_windows_ssh.rb, spec/unit/knife/bootstrap_options_spec.rb, spec/unit/knife/bootstrap_windows_winrm_spec.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Removed deprecated `--host-key-verification`, `--distro` & `--template-file` option.
- `--host-key-verify` is used now instead of `--host-key-verification`
- `--bootstrap-template-file` is used now instead of  `--distro` & `--template-file`
Fixes https://github.com/chef/knife-windows/issues/469
=> Removed deprecated host_key_verification, distro and template_file options

.travis.yml, appveyor.yml, knife-windows.gemspec
We're requiring Chef 14, which is Ruby 2.4 or later.
=> Require Ruby 2.4 or later

lib/chef/knife/core/windows_bootstrap_context.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
Set `log_level` to `:auto` in `client.rb` in windows to make it consistent with other platform
Fixes #231
=> fix log_level incosistency

knife-windows.gemspec
knife-windows v3 removes `knife bootstrap windows winrm` and `knife
boostrap windows ssh` in favor of the functionality moved into core with
Chef Infra 15. We wouldn't want anyone using earlier versions of Chef to
pull in this release.
Signed-off-by: Bryan McLellan <btm@loftninjas.org>
=> Require Chef Infra 15

lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/bootstrap_windows_ssh.rb, lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/windows_cert_generate.rb, lib/chef/knife/windows_cert_install.rb, lib/chef/knife/windows_helper.rb, lib/chef/knife/windows_listener_create.rb, lib/chef/knife/winrm.rb, lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/wsman_test.rb
require_relative is significantly faster and should be used when available.
=> Substitute require for require_relative

lib/chef/knife/winrm_knife_base.rb, lib/chef/knife/winrm_shared_options.rb, spec/unit/knife/winrm_spec.rb
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
Multiple servers can connect now using knife winrm command with and without providing an `--concurrency The number of allowed concurrent connection` option along with your `--manual-list QUERY is a space separated list of servers` option
https://github.com/chef/knife-windows/issues/445
https://github.com/chef/knife-windows/issues/402
- [*] New functionality includes tests
- [*] All tests pass
- [*] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
=> Fix multiple session issue of concurrency flag

Rakefile, lib/chef/knife/bootstrap_windows_base.rb, lib/chef/knife/bootstrap_windows_ssh.rb, lib/chef/knife/bootstrap_windows_winrm.rb, lib/chef/knife/knife_windows_base.rb, lib/chef/knife/windows_cert_generate.rb, lib/chef/knife/windows_helper.rb, lib/chef/knife/windows_listener_create.rb, lib/chef/knife/winrm.rb, lib/chef/knife/winrm_base.rb, lib/chef/knife/winrm_session.rb, lib/chef/knife/winrm_shared_options.rb, lib/chef/knife/wsman_test.rb, spec/spec_helper.rb, spec/unit/knife/windows_cert_generate_spec.rb, spec/unit/knife/winrm_session_spec.rb, spec/unit/knife/winrm_spec.rb, spec/unit/knife/wsman_test_spec.rb
Make sure things like the knife deps is everywhere, but don't depend on things we don't need and lazily depend on whatever we can.
WARNING: This is going to need a good deal of hand testing before it's ready for prime time since the spec coverage here needs some work.
=> Require libraries only where we need them

lib/chef/knife/winrm.rb
This is the longest loading knife plugin on my mac and adds .3 seconds
to every knife command run on the system
=> Lazy load winrm_session for speedup

lib/chef/knife/helpers/winrm_session.rb
This shaves another 2 seconds off of loading knife commands. We just need `winrm-elevated` which then requires `winrm`.
Signed-off-by: mwrock <matt@mattwrock.com>
=> autoload winrm

.expeditor/verify.pipeline.yml, Gemfile
The chef/chef repo needs to inject itself via ENV vars into the
Gemfile of this repo
(We have been uselessly testing knife-windows against the last release of chef/chef on every PR
in that repo instead of testing against the submitted code)
=> Support external testing

.expeditor/verify.pipeline.yml, Gemfile, knife-windows.gemspec
updated ruby version to 3.1 and removed 2.7 and 3.0 ruby verify pipeline as the latest chef 18.2.7 supports ruby >= 3.1
=> CHEF-1917 Fixed the knife-windows verify test failure

knife-windows.gemspec
An update to REXML breaks the wsman testing. Here we pin the older version which works for Chef-17.
=> Updating rxml dependency

Gemfile, lib/chef/knife/wsman_test.rb
ReXML 3.3.2 broke the knife-windows functionality by [adding a `REXML::ParseException` `raise`](https://github.com/ruby/rexml/compare/v3.2.6...v3.3.4#diff-f8c7cdefc29090ed525a2be70411ce741d4124853cf6425db7d18a6ea3bb9bb3R233)
Handle that exception and return an error message as before.
Supercedes #527, leaving #526 with the old behavior and a ReXML pin to v3.2.6
=> Handle REXML exception
