- lib/chef/knife/winrm.rb
- spec/unit/knife/winrm_spec.rb
Removed domain related validation with respective negotiate protocol and fixed/added unit tests.
> Remove domain name and Negotiate protocol validations

- lib/chef/knife/winrm.rb
- lib/chef/knife/winrm_base.rb
- spec/unit/knife/winrm_spec.rb
Changes to display default values for winrm_authentication_protocol option in CLI help.
> Update winrm_authentication_protocol option

- lib/chef/knife/windows_listener_create.rb
- spec/unit/knife/windows_listener_create_spec.rb
Removed basic_auth enable/disable from listener create.
> Removed winrm basic_auth enable/disable from listener create command

- .travis.yml
This will fix the tests running in Travis
> Update Rubies, removing unsupported 1.9.x

- lib/chef/knife/bootstrap_windows_winrm.rb
> Pass `ssl_verify_mode` bootstrap config to WinRM command

- lib/chef/knife/windows_cert_generate.rb
wrt: https://github.com/chef/knife-windows/issues/200
> Gender neutral message

- lib/chef/knife/windows_cert_generate.rb
- spec/unit/knife/windows_cert_generate_spec.rb
There's more work that could be done here, but I'm just trying to improve this while fixing a failing test that was based on the text output (https://travis-ci.org/chef/knife-windows/jobs/53077276).
@ksubrama @jdmundrawala @adamedx
> DRY up knife windows cert generate tests

- lib/chef/knife/bootstrap/windows-chef-client-msi.erb
- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
- spec/functional/bootstrap_download_spec.rb
options changes- encrypted_data_bag_secret and encrypted_data_bag_secret_file to secret & secret_file respectively.
Issue Reference- https://github.com/chef/knife-windows/issues/193
> Added chef options consistency changes

- appveyor.yml
this probably fixes appveyor in master by caching gems? It went green at least.
@jdmundrawala? /cc @ksubrama @smurawski
> run bundle install 3 times

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/bootstrap_windows_ssh.rb
- spec/spec_helper.rb
- spec/unit/knife/bootstrap_options_spec.rb
https://github.com/chef/oc_post_mortems/blob/master/2015/03/knife-windows-chef-12.md#corrective-actions
> Knife bootstrap flag comparison test.

- README.md
Clarification of what is meant by both of the windows bootstrap subcommands.
> Clarification in BOOTSTRAP TEMPLATES section

- lib/chef/knife/bootstrap_windows_base.rb
See also https://github.com/chef/chef/pull/3662
> Make debugging of bootstrap easier

- lib/chef/knife/bootstrap_windows_base.rb
Reverts chef/knife-windows#264 because of logging all of the seekrits!
> Revert "Make debugging of bootstrap easier"

- lib/chef/knife/bootstrap_windows_base.rb
- spec/unit/knife/bootstrap_windows_winrm_spec.rb
Code changes testing is in Progress for this PR.
> Fix for secret-file not being rendered in knife windows.

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
- spec/spec_helper.rb
- spec/unit/knife/bootstrap_options_spec.rb
This aligns tag support with recent merges to chef core and fixes build breaks in this gem
> Adding tags support to bootstrapping

- Rakefile
- appveyor.yml
The default task will continue to call both tasks so ci remains the same
> separate unit and functional specs to different tasks

- lib/chef/knife/winrm.rb
- spec/unit/knife/winrm_spec.rb
The current authentication failure messaging is specific to basic authentication and provides advise for turning off encryption on the target node. Failures for Negotiate authentication are not caught and just surface the `WinRMAuthorizationError`. This PR specifically catches `WinRMAuthorizationError` and provides a different Hint to the user when not using Basic auth.
> Improve error handling for non basic authentication

- lib/chef/knife/winrm_knife_base.rb
- spec/unit/knife/winrm_spec.rb
This PR will be easier to view after #282 is merged.
> Prevent ssl warning when not using ssl

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/knife_windows_base.rb
- lib/chef/knife/winrm.rb
- lib/chef/knife/winrm_base.rb
- lib/chef/knife/winrm_knife_base.rb
> Rebase of remove duplicate locate config #287

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/bootstrap_windows_winrm.rb
- lib/chef/knife/winrm_knife_base.rb
- spec/functional/bootstrap_download_spec.rb
- spec/unit/knife/bootstrap_options_spec.rb
- spec/unit/knife/bootstrap_windows_winrm_spec.rb
> fixes #295 adding bootstrap support for policy

- .travis.yml
- lib/chef/knife/bootstrap_windows_ssh.rb
- lib/chef/knife/winrm_base.rb
- spec/spec_helper.rb
- spec/unit/knife/bootstrap_options_spec.rb
added a couple small tweaks to #320
> Test fixes for chef's update of identity_file -> ssh_identity_file

- CHANGELOG.md
- lib/knife-windows/version.rb
This needs to go with #317, #326 and #325
> prepping for 1.1.2 release

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
Reverts chef/knife-windows#337
> Revert "Add fips flag to boostrap"

- CHANGELOG.md
- README.md
- lib/chef/knife/bootstrap/windows-chef-client-msi.erb
- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/winrm_knife_base.rb
- lib/chef/knife/winrm_session.rb
- spec/functional/bootstrap_download_spec.rb
- spec/spec_helper.rb
- spec/unit/knife/bootstrap_template_spec.rb
- spec/unit/knife/bootstrap_windows_winrm_spec.rb
This is ready for review.
\cc @smurawski @mwrock @adamedx @chefsalim @randomcamel
> Adding the ability for users to specify the architecture (64 or 32 bit) of Chef that they want installed during bootstrapping

- spec/unit/knife/bootstrap_windows_winrm_spec.rb
This is needed for extenal tests in https://github.com/chef/chef/pull/4880 to pass
> fix tests with fips check

- lib/chef/knife/core/windows_bootstrap_context.rb
- spec/assets/win_template_rendered_with_bootstrap_install_command.txt
- spec/assets/win_template_rendered_with_bootstrap_install_command_on_12_5_client.txt
- spec/assets/win_template_rendered_without_bootstrap_install_command.txt
- spec/assets/win_template_rendered_without_bootstrap_install_command_on_12_5_client.txt
Hi, I'm trying to get a machine to bootstrap from behind a proxy with knife[:bootstrap_proxy] set in my knife.rb and the powershell script didn't pick up the environment vars.
> Adding a proxy env var to wget.ps1

- Gemfile
- lib/chef/knife/bootstrap/windows-chef-client-msi.erb
- lib/chef/knife/bootstrap_windows_base.rb
- spec/functional/bootstrap_download_spec.rb
- spec/unit/knife/bootstrap_options_spec.rb
- spec/unit/knife/bootstrap_windows_winrm_spec.rb
w.r.t. https://github.com/chef/knife-windows/issues/372
> Fixing bootstrap via ssh regression

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/bootstrap_windows_ssh.rb
- lib/chef/knife/bootstrap_windows_winrm.rb
- spec/unit/knife/bootstrap_windows_winrm_spec.rb
Fix for issue https://github.com/chef/knife-windows/issues/378
> Add validation for FQDN value

- CHANGELOG.md
- lib/knife-windows/version.rb
Signed-off-by: Matt Wrock <matt@mattwrock.com>
> Release 1.7.0

- CHANGELOG.md
- lib/knife-windows/version.rb
Signed-off-by: Matt Wrock <matt@mattwrock.com>
> release 1.7.1

- lib/chef/knife/core/windows_bootstrap_context.rb
- spec/assets/win_template_rendered_with_bootstrap_install_command.txt
- spec/assets/win_template_rendered_with_bootstrap_install_command_on_12_5_client.txt
- spec/assets/win_template_rendered_without_bootstrap_install_command.txt
- spec/assets/win_template_rendered_without_bootstrap_install_command_on_12_5_client.txt
- spec/unit/knife/core/windows_bootstrap_context_spec.rb
> Added value for config_log_level and config_log_location

- CHANGELOG.md
- knife-windows.gemspec
Don't ship some docs and test files we don't need in the gem.
> Slim down the size of the install and the gem

- lib/chef/knife/bootstrap/windows-chef-client-msi.erb
- spec/unit/knife/bootstrap_options_spec.rb
Adds #448 
Tested the changes. 
Fixed failing specs.
Closes #448 
Fixes #439
> Detect if chef-client is already present

- .expeditor/config.yml
Tom added the ability to bump here.
> Setup Expeditor to handle major version bumping

- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/bootstrap_windows_ssh.rb
- lib/chef/knife/bootstrap_windows_winrm.rb
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>
Load dependency required files for knife bootstrap class. 
https://github.com/chef/knife-windows/issues/479
> Load bootstrap dependency

- README.md
- Update README as Chef OSS Best Practices
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>
> Update README.md as per Chef OSS Best Practices

- .expeditor/verify.pipeline.yml
> Run tests on Windows

- .rubocop.yml
- Gemfile
- Rakefile
- knife-windows.gemspec
- lib/chef/knife/bootstrap_windows_base.rb
- lib/chef/knife/bootstrap_windows_ssh.rb
- lib/chef/knife/bootstrap_windows_winrm.rb
- lib/chef/knife/knife_windows_base.rb
- lib/chef/knife/windows_cert_generate.rb
- lib/chef/knife/windows_cert_install.rb
- lib/chef/knife/windows_helper.rb
- lib/chef/knife/windows_listener_create.rb
- lib/chef/knife/winrm.rb
- lib/chef/knife/winrm_base.rb
- lib/chef/knife/winrm_knife_base.rb
- lib/chef/knife/winrm_session.rb
- lib/chef/knife/winrm_shared_options.rb
- lib/chef/knife/wsman_endpoint.rb
- lib/chef/knife/wsman_test.rb
- lib/knife-windows/version.rb
- spec/dummy_winrm_connection.rb
- spec/spec_helper.rb
- spec/unit/knife/windows_cert_generate_spec.rb
- spec/unit/knife/windows_cert_install_spec.rb
- spec/unit/knife/windows_listener_create_spec.rb
- spec/unit/knife/winrm_session_spec.rb
- spec/unit/knife/winrm_spec.rb
- spec/unit/knife/wsman_test_spec.rb
> Apply Chefstyle and enforce style

- Gemfile
- spec/spec_helper.rb
> Remove extra test deps we don't need

- lib/chef/knife/windows_helper.rb
- spec/unit/knife/winrm_session_spec.rb
- spec/unit/knife/winrm_spec.rb
Make sure we have the deps here
> Fix failures loading the banner

- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
- lib/chef/knife/helpers/bootstrap_windows_base.rb
> Don't try to require the removed lib

- lib/chef/knife/helpers/bootstrap_windows_base.rb
> Fix an include of the removed library

- knife-windows.gemspec
- lib/chef/knife/windows_cert_generate.rb
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
Attempt to get CI green again. #506 #507
> Fix chefstyle violations.

- knife-windows.gemspec
- lib/chef/knife/windows_listener_create.rb
- spec/unit/knife/windows_listener_create_spec.rb
This just introduces something we can easier stub since $? is
apparently now considered frozen and rspec cannot stub it.
> Fix test for ruby-3.0

- lib/chef/knife/helpers/winrm_knife_base.rb
Signed-off-by: sanga17 <sausekar@msystechnologies.com>
knife winrm errors with **'undefined method echo'**
Fixed: i) https://github.com/chef/knife-windows/issues/513
> Fixed knife winrm fails with echo as undefined

- knife-windows.gemspec
- spec/spec_helper.rb
This can no longer dep on chef itself
> Require Ruby 2.7+ and the knife gem

- .github/CODEOWNERS
Signed-off-by: Vikram Karve <vikram.karve@progress.com>
The workstation team will maintain knife and its plugins going forward.
> update code owners to workstation team

- knife-windows.gemspec
- lib/chef/knife/helpers/winrm_session.rb
Replaced `winrm ~> 2.1` and `winrm-elevated ~> 1.0` with `chef-winrm ~> 2.3` and `chef-winrm-elevated ~> 1.2`
JIRA: https://progresssoftware.atlassian.net/browse/CHEF-20515
> use chef-winrm and chef-winrm-elevated
